use_frameworks!

platform :ios, '9.0'

target 'GHI_Example' do
  pod 'GHI', :path => '../'

  target 'GHI_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
